### ISSUE TITLE
Example value of 00 fails

### ISSUE THREAD

**Issue by splummer** [thespain/thespain-veeamagent#4]
Example value of 00 fails with error 

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: {"message":"Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: A substring operation does not accept a String as a character index. Expected an Integer at /etc/puppetlabs/code/environments/INF_207_Veeam_Login/modules/veeamagent/manifests/preinstall.pp:4:23 at /etc/puppetlabs/code/environments/INF_207_Veeam_Login/site/profile/manifests/veeam_linux_client.pp:113 on node plummertest1.geneseo.edu","issue_kind":"RUNTIME_ERROR","stacktrace":["Warning: The 'stacktrace' property is deprecated and will be removed in a future version of Puppet. For security reasons, stacktraces are not returned with Puppet HTTP Error responses."]}`

**Comment by splummer** [comment]
Turns out an old version of facter returns invalid values. Please disregard.

**Comment by yachub** [comment]
Hi @splummer, Thanks for the info and finding this out. Please let me know if you have any further issues.

-Jake
