### ISSUE TITLE
Support v2 agents

### ISSUE THREAD

**Issue by genebean** [thespain/thespain-veeamagent#6]
It looks like there are some new settings for `veeam.ini` as part of the v2 agents that will need to be incorporated into `veeam.ini.epp`

**Comment by genebean** [comment]
Starting work on this today.

**Comment by genebean** [comment]
Testing of an updated template against nodes that had their agent deployed from the Veeam console showed some fairly major issues including changing values added to the config by the deployment. The result of this discovery is that I am starting on a different approach that is more compatible with agents being deployed via the Veeam console.

**Comment by genebean** [comment]
I've got a function type and provider working and am now working to adapt the rest of the code to support it.

**Comment by genebean** [comment]
#8 will resolve this.

**Comment by yachub** [comment]
#8 has been merged and published to the Puppet Forge. This was a major improvement to how the module works, thank you for the effort!
